#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: LED and Flashlight commands
Team Members: 3
Date: 11/12/24
Section: 3


Task Description: Turn on the LED and flashlight for 10 seconds.


Pseudocode:
turn LED on
Turn Flashlight on
Wait 10 seconds
Turn LED off
Turn Flashlight off

*/

task main()
{                                     //Program begins, insert code within curly braces
	turnLEDOn(green);											//Turn green LED on
	turnFlashlightOn(flashlight, 127);    // Flashlight on with full brightness
	wait(10);															//10 second wait for the LED and flashlight
	turnLEDOff(green);                    //Turn green LED off
	turnFlashlightOff(flashlight);        //Turn flashlight off

}
