#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: LED and Flashlight commands
  Team Members: teamnummber
  Date: 11/12/24
  Section: teamnumber


  Task Description: Turn on the LED and flashlight for 10 seconds.


  Pseudocode:
  turn LED on
  Turn Flashlight on
  Wait 10 seconds
  Turn LED off
  Turn Flashlight off

*/

task main()
{                                     //Program begins, insert code within curly braces



}
